#!/bin/bash
# Commit hook to load modified XML files to the configured BaseX repository
#
# Needs to handle the following cases:
#
# Addition of new files or updates to existing files
# Deletion of existing files
# Note that the --diff-filter=R (renamed) option doesn't
# seem to actually report renames, so renamed files are
# reported as a delete+add.
#
#

# BaseX connection parameters:

baseXUser="admin"
baseXPW="admin"
basexPort="1984"
basexServer="localhost"
basexDatabase="sample-project"
basexOptions=( -U "$baseXUser" -P "$baseXPW" -p "$basexPort" -n "$basexServer" )

# Get the list of changed files.
# Each line is of the form
# {status}   {path}
#
# E.g.:
#
# M       documentation/topics/tools-basex.dita
#

# Current directory is the repository root:

topDir=$PWD

addOrUpdate() { git diff HEAD^ HEAD --name-only --diff-filter=AM; }

# echo "Adding/Updating files:"
addOrUpdate | while read -r line; do
   cmd=( basexclient -c "OPEN $basexDatabase; REPLACE $line $topDir/$line; EXIT" "${basexOptions[@]}" )
   # printf 'Running: '; printf '%q ' "${cmd[@]}"; printf '\n'
   "${cmd[@]}"
done 

deleted() { git diff HEAD^ HEAD --name-only --diff-filter=D; }

# echo "Deleing files:"
deleted | while read -r line; do
   cmd=( basexclient -c "OPEN $basexDatabase; DELETE $line; EXIT" "${basexOptions[@]}" )
   # printf 'Running: '; printf '%q ' "${cmd[@]}"; printf '\n'
   "${cmd[@]}"
done 



