#!/usr/bin/ruby
#
# DITA for Small Teams 
#
# Post-receive server-side git hook
# to update DFST Link Management database
# with any changes as a result of updates
# to the repository.
#--------------------------------------------
#
# In the context of the docker containers the network details
# are invariant.
require 
#
# End of script
#